name: Trivy IaC Scan (CloudFormation)

on:
  push:
    branches:
      - main

jobs:
  trivy-iac-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy IaC scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: "config"
          scan-ref: "."
          severity: ${{ inputs.severity }}
          format: "sarif"
          output: "trivy-scan.sarif"
          exit-code: "0"

      - name: Download Trivy Scan Report Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan
          path: trivy-scan.sarif
